[2024-02-06T17:30:01.477+0900] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: naver-search-pipeline.is_api_available __airflow_temporary_run_2024-02-06T08:29:58.108581+00:00__ [queued]>
[2024-02-06T17:30:01.480+0900] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: naver-search-pipeline.is_api_available __airflow_temporary_run_2024-02-06T08:29:58.108581+00:00__ [queued]>
[2024-02-06T17:30:01.480+0900] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-06T17:30:01.490+0900] {taskinstance.py:1327} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-02-06 00:00:00+00:00
[2024-02-06T17:30:01.492+0900] {standard_task_runner.py:57} INFO - Started process 126379 to run task
[2024-02-06T17:30:01.493+0900] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'naver-search-pipeline', 'is_api_available', '__airflow_temporary_run_2024-02-06T08:29:58.108581+00:00__', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/naver_search_pipeline.py', '--cfg-path', '/tmp/tmpqgqqk20a']
[2024-02-06T17:30:01.494+0900] {standard_task_runner.py:85} INFO - Job 8: Subtask is_api_available
[2024-02-06T17:30:01.511+0900] {task_command.py:410} INFO - Running <TaskInstance: naver-search-pipeline.is_api_available __airflow_temporary_run_2024-02-06T08:29:58.108581+00:00__ [running]> on host localhost
[2024-02-06T17:30:01.546+0900] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='naver-search-pipeline' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='__airflow_temporary_run_2024-02-06T08:29:58.108581+00:00__'
[2024-02-06T17:30:01.547+0900] {http.py:122} INFO - Poking: v1/search/local.json
[2024-02-06T17:30:01.549+0900] {base.py:73} INFO - Using connection ID 'naver_search_api' for task execution.
[2024-02-06T17:30:01.687+0900] {logging_mixin.py:150} INFO - {'lastBuildDate': 'Tue, 06 Feb 2024 17:30:01 +0900', 'total': 5, 'start': 1, 'display': 5, 'items': [{'title': '은주정', 'link': 'https://www.instagram.com/eunjujeong1986', 'category': '한식>찌개,전골', 'description': '', 'telephone': '', 'address': '서울특별시 중구 주교동 43-23', 'roadAddress': '서울특별시 중구 창경궁로8길 32', 'mapx': '1269997477', 'mapy': '375686783'}, {'title': '김촌 서울대입구 직영점', 'link': '', 'category': '음식점>한식', 'description': '', 'telephone': '', 'address': '서울특별시 관악구 봉천동 855-10 1층', 'roadAddress': '서울특별시 관악구 관악로14길 6 1층', 'mapx': '1269528715', 'mapy': '374791672'}, {'title': '한대패', 'link': 'https://www.instagram.com/uglyhome_busan', 'category': '음식점>한식', 'description': '', 'telephone': '', 'address': '부산광역시 부산진구 부전동 519-30 1층', 'roadAddress': '부산광역시 부산진구 가야대로784번길 46-11 1층', 'mapx': '1290565274', 'mapy': '351553749'}, {'title': '한일옥', 'link': '', 'category': '음식점>한식', 'description': '', 'telephone': '', 'address': '전북특별자치도 군산시 신창동 2-1', 'roadAddress': '전북특별자치도 군산시 구영3길 63', 'mapx': '1267082416', 'mapy': '359874893'}, {'title': '굴다리식당', 'link': '', 'category': '음식점>한식', 'description': '', 'telephone': '', 'address': '서울특별시 마포구 도화동 181-45', 'roadAddress': '서울특별시 마포구 새창로 8-1', 'mapx': '1269508191', 'mapy': '375421254'}]}
[2024-02-06T17:30:31.770+0900] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-02-06T17:30:31.773+0900] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 126379. PIDs of all processes in the group: [126379]
[2024-02-06T17:30:31.773+0900] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 126379
[2024-02-06T17:30:31.773+0900] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-02-06T17:30:31.778+0900] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/shan/anaconda3/envs/airflow_env/lib/python3.7/site-packages/airflow/sensors/base.py", line 253, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/shan/anaconda3/envs/airflow_env/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-02-06T17:30:31.780+0900] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=naver-search-pipeline, task_id=is_api_available, execution_date=20240206T000000, start_date=20240206T083001, end_date=20240206T083031
[2024-02-06T17:30:31.784+0900] {standard_task_runner.py:109} ERROR - Failed to execute job 8 for task is_api_available ((sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('is_api_available', 'naver-search-pipeline', '__airflow_temporary_run_2024-02-06T08:29:58.108581+00:00__', -1, '2024-02-06 08:30:01.477251', '2024-02-06 08:30:31.779820', 30)]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 126379)
[2024-02-06T17:30:31.787+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=126379, status='terminated', exitcode=1, started='17:30:00') (126379) terminated with exit code 1
