[2024-02-07T13:13:44.065+0900] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: naver-search-pipeline.store_naver scheduled__2024-02-06T00:00:00+00:00 [queued]>
[2024-02-07T13:13:44.068+0900] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: naver-search-pipeline.store_naver scheduled__2024-02-06T00:00:00+00:00 [queued]>
[2024-02-07T13:13:44.068+0900] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-07T13:13:44.078+0900] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): store_naver> on 2024-02-06 00:00:00+00:00
[2024-02-07T13:13:44.080+0900] {standard_task_runner.py:57} INFO - Started process 144991 to run task
[2024-02-07T13:13:44.081+0900] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'naver-search-pipeline', 'store_naver', 'scheduled__2024-02-06T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/naver_search_pipeline.py', '--cfg-path', '/tmp/tmpoxnbwie3']
[2024-02-07T13:13:44.082+0900] {standard_task_runner.py:85} INFO - Job 14: Subtask store_naver
[2024-02-07T13:13:44.100+0900] {task_command.py:410} INFO - Running <TaskInstance: naver-search-pipeline.store_naver scheduled__2024-02-06T00:00:00+00:00 [running]> on host localhost
[2024-02-07T13:13:44.135+0900] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='naver-search-pipeline' AIRFLOW_CTX_TASK_ID='store_naver' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-06T00:00:00+00:00'
[2024-02-07T13:13:44.136+0900] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-07T13:13:44.136+0900] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo -e ".separator ","\n.import /home/shan/airflow/dags/data/processed_result.csv naver_search_result" | sqlite3 /home/shan/airflow/airflow.db']
[2024-02-07T13:13:44.139+0900] {subprocess.py:86} INFO - Output:
[2024-02-07T13:13:44.140+0900] {subprocess.py:93} INFO - Error: cannot open "/home/shan/airflow/dags/data/processed_result.csv"
[2024-02-07T13:13:44.140+0900] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-07T13:13:44.144+0900] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/shan/anaconda3/envs/airflow_env/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-07T13:13:44.145+0900] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=naver-search-pipeline, task_id=store_naver, execution_date=20240206T000000, start_date=20240207T041344, end_date=20240207T041344
[2024-02-07T13:13:44.153+0900] {standard_task_runner.py:109} ERROR - Failed to execute job 14 for task store_naver (Bash command failed. The command returned a non-zero exit code 1.; 144991)
[2024-02-07T13:13:44.172+0900] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-02-07T13:13:44.179+0900] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
